# GitHub Sponsors configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button

github: [lchtangen]
# patreon: samplemindai
# ko_fi: samplemindai
# custom: ["https://samplemind.ai/sponsor"]

